service: gin-rating-api

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-2
  endpointType: regional
  versionFunctions: false

package:
individually: true
exclude:
  - ./**

functions:
  api:
    handler: bin/api
    memorySize: 256
    timeout: 15
    reservedConcurrency: 5
    package:
      include:
        - ./bin/api
    events:
      - http:
          path: /{proxy+}
          method: ANY
          authorizer: 
             type: COGNITO_USER_POOLS
             authorizerId: 
               Ref: ApiGatewayAuthorizer

resources:
  Resources:
    ApiGatewayAuthorizer: 
      Type: AWS::ApiGateway::Authorizer
      Properties: 
        Name: ${self:custom.stage}-gin-rating-authorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId: 
          Ref: ApiGatewayRestApi
        ProviderARNs: 
          - Fn::GetAtt:
              - GinRatingUserPool
              - Arn

    GinRatingUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.stage}-gin-rating-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    GinRatingUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.stage}-gin-rating-user-pool-client
        UserPoolId:
          Ref: GinRatingUserPool
        GenerateSecret: false